### ISSUE TITLE
Re-integrate tests in 9.0.0 branch

### ISSUE THREAD

**Issue by abhinayagarwal** [controlsfx/controlsfx#1168]
ControlsFX 9.0.0 is getting rid of 2 test classes:

* org.controlsfx.control.JavaFXThreadingRule
* org.controlsfx.control.SearchableComboBoxTest

JavaFXThreadingRule
---

`JavaFXThreadingRule` uses `javafx.swing` module to run tests. Since we do not want to include one extra module just for one test case, it is a good trade-off to remove it unless we have a better reason to integrate it back (or more tests which depend on the said module).

SearchableComboBoxTest
----

`SearchableComboBoxTest` is written using TestFX. For some reason this doesn't work on JDK 9. If someone has experience with TestFX + JDK 9. We could bring this test back.

**Comment by brcolow** [comment]
Working on this in https://github.com/TestFX/TestFX/pull/669 - really need to read a Jigsaw book I think, lol.

**Comment by brcolow** [comment]
I merged https://github.com/TestFX/TestFX/pull/669 into master. Would it be possible for you to test against latest master? I am hesitant to issue a release without *some* real life testing.

**Comment by abhinayagarwal** [comment]
Hi @brcolow ,

I can definitely test it out. Is there a snapshot build on Maven Central  or somewhere else which I can use?

**Comment by brcolow** [comment]
@abhinayagarwal I don't think TestFX snapshots are properly released. Give me one day and tomorrow I'll investigate getting them turned on.

**Comment by brcolow** [comment]
Published the snapshot: https://oss.sonatype.org/content/repositories/snapshots/org/testfx/ - note that I compiled it with Java 12 so it may only work on a Java 12 VM. Let me know, I can change that and publish another.

**Comment by abhinayagarwal** [comment]
I finally got some time to test the new snapshot release. It seems that one of the dependencies `hamcrest` is still not modularised and is found in 2 packages:

```
...
error: the unnamed module reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module hamcrest.junit reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module javafx.controlsEmpty reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module javafx.mediaEmpty reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module javafx.graphicsEmpty reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module javafx.baseEmpty reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module org.osgi.core reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module java.hamcrest reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module junit reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module org.testfx.junit reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module org.hamcrest reads package org.hamcrest from both java.hamcrest and org.hamcrest
error: module org.testfx reads package org.hamcrest from both org.hamcrest and java.hamcrest

controlsfx/controlsfx/src/main/java/module-info.java:1: error: module org.controlsfx.controls reads package org.hamcrest from both java.hamcrest and org.hamcrest
module org.controlsfx.controls {
^
13 errors
...
```

**Comment by abhinayagarwal** [comment]
@brcolow One more thing, [pom](https://oss.sonatype.org/content/repositories/snapshots/org/testfx/testfx-core/4.0.17-alpha-SNAPSHOT/testfx-core-4.0.17-alpha-20190815.172336-1.pom) for the new snapshots explicitly declare the classifier. This should not be the case.

In case you are using the JavaFX Gradle plugin, this is an known issue. In ControlsFX, we explicitly [remove the classifier from the pom](https://github.com/controlsfx/controlsfx/blob/9.0.0/mavenPublish.gradle#L92).

**Comment by brcolow** [comment]
@abhinayagarwal I had to do some crazy stuff to exclude the old hamcrest from Junit 4. Does controlsfx use JUnit 4? Are you sure there isn't some transitive dependency pulling in the old hamcrest?

See [here](https://github.com/TestFX/TestFX/blob/master/subprojects/testfx-core/testfx-core.gradle#L43) for the craziness I copy pasted to fix new hamcrest with Junit 4.

Good catch about the classifiers thing. I will open (and merge) a PR that should fix that aspect of your feedback.

**Comment by abhinayagarwal** [comment]
It seems that `testfx-junit` has a dependency on `hamcrest-junit` which in turn depends on Junit 4.

**Comment by brcolow** [comment]
Correct. The purpose of the [craziness](https://github.com/TestFX/TestFX/blob/master/subprojects/testfx-core/testfx-core.gradle#L43) I linked is so that the JUnit 4 transitive dependency pulls in the latest hamcrest (not the old). Perhaps it is not doing it's job for downstream testfx-junit consumers.

**Comment by brcolow** [comment]
@abhinayagarwal Will have a new snapshot with the classifier and hamcrest-junit dependency removed :). Thanks for your help!

**Comment by brcolow** [comment]
@abhinayagarwal Just merged https://github.com/TestFX/TestFX/pull/680 which removes the `hamcrest-junit` dependency. Let me know if you can test it :).

**Comment by abhinayagarwal** [comment]
@brcolow Just tried it out. We have definitely made some progress here. Although, I am still unable to use the library. Here are my findings so far:

TestFX-Core has a compile time dependency on `hamcrest-core` and a transitive dependency on `hamcrest` libraries. Both these jars have a package `org.hamcrest`. Therefore, if I add `requires org.hamcrest;` to `module-info.java`, the IDE warns me that the module is present in both jars. If I ignore the warning and run the tests, I get the following exception:

```
controlsfx/controlsfx/src/test/java/org/controlsfx/control/SearchableComboBoxTest.java:74: error: cannot access Matcher
        comboBox = robot.lookup("#comboBox").query();
                        ^
  class file for org.hamcrest.Matcher not found
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

I should be able to make this work by patching the modules. Although, my inexperience with `--patch-modules` is currently a hindrance.

One question though:  [Matcher/Assertions Library section in TextFX ReadME](https://github.com/TestFX/TestFX#matcherassertions-library-1) says that we could use *either* hamcrest or assert4j with TestFX, where as TestFX has a compile time dependency on both of them. Is this expected?

**Comment by brcolow** [comment]
@abhinayagarwal Thanks for your patience and assistance with this.

I removed the `hamcrest-core` dependency from testfx-core, snapshot should be up shortly: https://github.com/TestFX/TestFX/pull/681

I don't see a way to make AssertJ a non-compile time dependency, unless I am missing something. I should clarify that in the README.

**Comment by abhinayagarwal** [comment]
I was still getting the same previously stated error about not able to find `org.hamcrest.Matcher` class. Both the hamcrest jars were still being brought in as transitive dependency. Therefore I made the following change to the `build.gradle`:

```
dependencies {
    implementation ("org.testfx:testfx-junit:4.0.17-alpha-SNAPSHOT") {
        exclude group: 'org.openjfx'
        exclude group: 'org.hamcrest'
    }
    implementation group: 'org.hamcrest', name: 'hamcrest', version: '2.1'
}
```

Then I had to add `requires static org.hamcrest;` to the `module-info.java`. Post this the Gradle was able to compile all the classes for test.

Current status is that while executing the test, it fails and _hangs_ with the following exception:

```
> Task :controlsfx:test FAILED
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module org.testfx contains package javafx.collections, module javafx.base exports package javafx.collections to org.testfx
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module org.testfx contains package javafx.collections, module javafx.base exports package javafx.collections to org.testfx
Process 'Gradle Test Executor 2' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 2' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:138)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:91)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy64.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:212)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:340)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:102)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:82)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:834)
```

In order to make it easier for you to test, I have committed the code on my fork of controlsfx. 

You can do the following to reproduce it:

* Clone: https://github.com/abhinayagarwal/controlsfx/
* Checkout branch 9.0.0
* Run: `./gradlew :controlsfx:test`

Hope it helps :)

**Comment by brcolow** [comment]
I now am getting:

```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module org.testfx contains package javafx.css, module javafx.graphics exports package javafx.css to org.testfx
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module org.testfx contains package javafx.scene.robot, module javafx.graphics exports package javafx.scene.robot to org.testfx
```

I don't understand why :(.

**Comment by brcolow** [comment]
I think one of the reasons this is failing is because the snapshot JAR contains all of our dependencies, regardless of if they are defined as `implementation` or `api`. I have no idea why it is in effect creating a Fat, Uber JAR containing everything.

**Comment by brcolow** [comment]
It seems like maven publish is creating a POM where every dependency is included as `runtime`...

**Comment by brcolow** [comment]
I think I found out why. It was the `bnd` plugin that I added as a somewhat futile attempt to keep `osgi` compatibility. Probably going to drop that for now.

**Comment by brcolow** [comment]
Still getting the following error when trying to run ControlsFX test on 9.0.0 branch:

```
java.lang.module.ResolutionException: Module org.testfx contains package javafx.stage, module javafx.graphics exports package javafx.stage to org.testfx
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module org.testfx contains package javafx.scene.effect, module javafx.graphics exports package javafx.scene.effect to org.testfx
```

Don't know how that's possible because the `testfx-core` JAR no longer contains any dependencies.

**Comment by abhinayagarwal** [comment]
May be we should create a simple modular project to test TestFX rather than using ControlsFX. Once we get things running there, we can test it again on ControlsFX.

**Comment by brcolow** [comment]
I have a simple test at https://github.com/brcolow/testfx-playground which works correctly when running `mvn package`.

**Comment by Mason-Chou** [comment]
Did this ever get resolved? I'm having issues running the gradle build script  ``./gradlew build check`` using Java 11 due to the reasons OP has mentioned.

**Comment by brcolow** [comment]
@Mason-Chou It has not been resolved, unfortunately. My free time to work on TestFX has been severely restricted as of late. Most of the ground work has been merged - it really is going to require someone to dig in and get the bottom of it.

**Comment by Mason-Chou** [comment]
@brcolow Thanks for the update! It's not a big deal for me as I can just add that dependecy in, but this issue is something to consider moving forward.
