### ISSUE TITLE
Running FXSampler 11.1.1

### ISSUE THREAD

**Issue by pseudo555** [controlsfx/controlsfx#1409]
Mannifest ask for a snapshot version:
Class-Path: javafx-web-13-linux.jar javafx-controls-13-linux.jar javafx-controls-13.jar javafx-media-13-linux.jar javafx-media-13.jar javafx-graphics-13-linux.jar javafx-graphics-13.jar javafx-base-13-linux.jar javafx-base-13.jar controlsfx-11.1.1.jar fxsampler-1.0.12-SNAPSHOT.jar

Which cannot be found... so how can we try the sampler ?

**Comment by pseudo555** [comment]
Same goes for:
* controlsfx-samples-11.1.0
* controlsfx-samples-11.1.1

**Comment by elQuero93** [comment]
Same here, running on JavaFX 11. Adding fxsampler-1.0.11 to the classpath does not solves the problem, obviously.

**Comment by abhinayagarwal** [comment]
Running a JavaFX application from a non-uber jar is not very easy. I recommend you clone the application and then use `./gradlew run` to run the sampler.

**Comment by elQuero93** [comment]
I think that the problem is not the jar thing (also because I test also on fat jars generated trough the 'com.github.johnrengelman.shadow' Gradle plugin) but the fact that the https://github.com/controlsfx/controlsfx/blob/e76c36d72c07808fd9f217aa0440de1b00fa8667/gradle.properties file contains a reference to the `1.0.12-SNAPSHOT` fxsampler package version, which has not been released.

Furthermore I think that the main class of the controlsfx-samples package is wrong, because is the main class of the fxsampler package. Here is the faulty file: https://github.com/controlsfx/controlsfx/blob/791365178119238940942c2cc5003e4bd166d346/controlsfx-samples/build.gradle

**Comment by pseudo555** [comment]
that's exactly my point : the snapshot dependencies requirement should never be present in any release.

**Comment by ggkids78** [comment]
Hello, I have the same issue. How could I solve it? I'm building a javafx 11 and maven.
Thank you.

**Comment by ggkids78** [comment]
Hello, any update about this issue?
Cheers.

**Comment by abhinayagarwal** [comment]
Does it resolve the issue, if we release `controlsfx-samples.jar` with dependency on non-snapshot version of the FXSampler?

A long term solution may be to update fxsampler project to have a non-final `FXSampler` class which can then be inherited by `controlsfx-samples` and other projects out there.

**Comment by pseudo555** [comment]
I think it should solve the issue. At least it worth trying.

**Comment by ggkids78** [comment]
I also think it should solve the issue, it's just a maven dependency complain. Thanks!

**Comment by garawaa** [comment]
samples.jar does not work

**Comment by garawaa** [comment]
generated jar files does not work

**Comment by pseudo555** [comment]
2 years later, FXSampler 1.0.12 is still not released... should we really have to compile it ourself ?
